POST http://localhost:3000/students
Content-Type: application/json

{
  "alumn_DNI": "12345678",
  "nombre": "Juan",
  "apellido": "Pérez",
  "asistencias": 20,
  "fecha_nac": "2000-01-01T00:00:00.000Z",
  "año": "segundo"
}